version: '3'

services:
  client:
    build:
      context: ../sensu/sensu-build
      dockerfile: Dockerfile-client
    #Image eh ignorado em modo swarm
    image: client:mailer-v1.4.3
    command: client
    environment:
      CLIENT_NAME: client1
      CLIENT_SUBSCRIPTIONS: all
      CLIENT_ADDRESS: 127.0.0.1
      TRANSPORT_NAME: rabbitmq
      CLIENT_KEEPALIVE_HANDLER: mailer
      CLIENT_DEREGISTER: 'false'
      #para acessar info do host e nao do container:
      HOST_DEV_DIR: /host_dev
      HOST_PROC_DIR: /host_proc
      HOST_SYS_DIR: /host_sys
    volumes:
     #Para que o container pegue info de monitoracao do host
     #e nao dele mesmo
     - "/dev:/host_dev/:ro"
     - "/proc:/host_proc/:ro"
     - "/sys:/host_sys/:ro"
    ports:
      - '3030:3030'
    networks:
      - default

networks:
  default:
    external:
      name: monitoring-service_default
