stages:
  - validation
  - build
  - deploy

deploy:
  stage: deploy
  script:
  - sed -i
       -e "s/SMTP_USER/${SMTP_USER}/"
       -e "s/SMTP_PASSWD/${SMTP_PASSWD}/"
       services/sensu/server/conf/handlers/mailer.json
    - docker stack deploy --compose-file docker-compose.yaml monitorStack
  only:
    - master
