---
version: '3'

services:

#Sensu server:
  server:
    build: ./services/sensu/server
    image: sensu-server-influxdb:1.4.3
    command: server
    environment:
      TRANSPORT_NAME: rabbitmq
      RUNTIME_INSTALL: 'mailer'
    volumes:
      - ./services/sensu/server/conf:/etc/sensu/conf.d
    depends_on:
      - rabbitmq
      - redis
      - api
    networks:
      - default

#Sensu api
  api:
    image: sstarcher/sensu:1.4.3
    command: api
    environment:
      TRANSPORT_NAME: rabbitmq
    ports:
      - '4567:4567'
    depends_on:
      - rabbitmq
      - redis
    networks:
      - default

#Redis: Database for sensu
  redis:
    image: redis:3
    networks:
      - default

#Rabbitmq: Message queue service
  rabbitmq:
    image: rabbitmq:3.7.8
    ports:
      - '5672:5672'
    networks:
      - default

#Uchiwa: Sensu's dashboard
  uchiwa:
    image: sstarcher/uchiwa:0.25.2
    environment:
      SENSU_DC_NAME: speed
      SENSU_HOSTNAME: api
    depends_on:
      - api
    ports:
      - '80:3000'
    networks:
      - default

#InfluxDB: database for collected metrics
  influxdb:
    image: influxdb:1.7.5
    environment:
      INFLUXDB_DB: 'sensu'
      INFLUXDB_ADMIN_ENABLED: 'true'
      INFLUXDB_ADMIN_USER: sensu
      INFLUXDB_ADMIN_PASSWORD: sensu
    volumes:
      - ./services/influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf
      - /srv/monitoring-service/influxdb-storage:/var/lib/influxdb
    ports:
      - '8086:8086'
    networks:
      - default

networks:
  default:
