--- 
version: '3'

services:

#Sensu server:
  server:
    image: sstarcher/sensu:1.4.3
    command: server
    environment:
      TRANSPORT_NAME: rabbitmq
      RUNTIME_INSTALL: 'mailer'
    volumes:
      - "./services/sensu/server/conf:/etc/sensu/conf.d"
    depends_on:
      - rabbitmq
      - redis
      - api
    networks:
      - default

#Sensu api
  api:
    image: sstarcher/sensu:1.4.3
    command: api
      - redis
    environment:
      TRANSPORT_NAME: rabbitmq
    ports:
      - '4567:4567'  
    depends_on:
      - rabbitmq
      - redis
    networks:
      - default

#Redis: Database for sensu
  redis:
    image: redis:3  
    networks:
      - default

#Rabbitmq: Message queue service
  rabbitmq:
    image: rabbitmq:3.7.8
    ports:
      - "5672:5672" 
    networks:
      - default

#Uchiwa: Sensu's dashboard
  uchiwa:
    image: sstarcher/uchiwa:0.25.2
    environment:
      SENSU_DC_NAME: speed
      SENSU_HOSTNAME: api
    depends_on:
      - api
    ports:
      - '80:3000'
    networks:
      - default
