---
version: '3'

services:

#Sensu server:
  server:
    build: ./sensu
    image: sensu:1.4.3
    command: server
    environment:
      TRANSPORT_NAME: rabbitmq
    volumes:
      - ./sensu/conf.d:/etc/sensu/conf.d
    depends_on:
      - rabbitmq
      - redis
      - api
    networks:
      - default

#Sensu api
  api:
    image: sstarcher/sensu:1.4.3
    command: api
    environment:
      TRANSPORT_NAME: rabbitmq
    ports:
      - '4567:4567'
    depends_on:
      - rabbitmq
      - redis
    networks:
      - default

#Redis: Database for sensu
  redis:
    image: redis:3
    networks:
      - default

#Rabbitmq: Message queue service
  rabbitmq:
    image: rabbitmq:3.7.8
    ports:
      - '5672:5672'
    networks:
      - default

#Uchiwa: Sensu's dashboard
  uchiwa:
    image: sstarcher/uchiwa:0.25.2
    environment:
      SENSU_DC_NAME: speed
      SENSU_HOSTNAME: api
    depends_on:
      - api
    ports:
      - '80:3000'
    networks:
      - default

#InfluxDB: database for collected metrics
  influxdb:
    image: influxdb:1.7.5
    environment:
      INFLUXDB_DB: sensu
      INFLUXDB_ADMIN_USER: sensu
      INFLUXDB_ADMIN_PASSWORD: sensu
      INFLUXDB_ADMIN_ENABLED: 'true'
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - influxdb-storage:/var/lib/influxdb
    ports:
      - '8086:8086'
    networks:
      - default

# Grafana: Data Visualization for collected metrics
  grafana:
    image: grafana/grafana:6.1.3
    environment:
      HOSTNAME: grafana
      GF_ANALYTICS_REPORTING_ENABLE: 'false'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_SIGNOUT_MENU: 'true'
    user: "0"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning 
      - grafana-storage:/var/lib/grafana  
    depends_on:
      - influxdb
    ports:
      - '3000:3000'
    networks:
      - default

networks:
  default:

volumes:
  influxdb-storage:
  grafana-storage:
