---
version: '3'

services:

# Sensu Server:
  server:
    build: ./sensu
    image: sensu:1.4.3
    command: server
    environment:
      TRANSPORT_NAME: rabbitmq
    volumes:
      - ./sensu/conf.d:/etc/sensu/conf.d
    depends_on:
      - rabbitmq
      - redis
      - api
    networks:
      - metricsnet

# Sensu API
  api:
    image: sstarcher/sensu:1.4.3
    command: api
    environment:
      TRANSPORT_NAME: rabbitmq
    ports:
      - '4567:4567'
    depends_on:
      - rabbitmq
      - redis
    networks:
      - metricsnet

# Redis: Sensu's Internal Database
  redis:
    image: redis:3
    networks:
      - metricsnet

# RabbitMQ: Sensu's Transport Service
  rabbitmq:
    image: rabbitmq:3.7.8
    ports:
      - '5672:5672'
    networks:
      - metricsnet

# Uchiwa: Sensu's Dashboard
  uchiwa:
    image: sstarcher/uchiwa:0.25.2
    environment:
      SENSU_DC_NAME: speed
      SENSU_HOSTNAME: api
    depends_on:
      - api
    ports:
      - '80:3000'
    networks:
      - metricsnet

# InfluxDB: Database for collected metrics
  influxdb:
    image: influxdb:1.7.6
    environment:
      INFLUXDB_DB: sensu
      INFLUXDB_ADMIN_USER: sensu
      INFLUXDB_ADMIN_PASSWORD: sensu
      INFLUXDB_ADMIN_ENABLED: 'true'
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - influxdb-storage:/var/lib/influxdb
    ports:
      - '8086:8086'
    networks:
      - metricsnet

# Grafana: Data Visualization for collected metrics
  grafana:
    image: grafana/grafana:6.1.3
    environment:
      HOSTNAME: grafana
      GF_ANALYTICS_REPORTING_ENABLE: 'false'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_SIGNOUT_MENU: 'true'
    user: "0"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning 
      - grafana-storage:/var/lib/grafana  
    depends_on:
      - influxdb
    ports:
      - '3000:3000'
    networks:
      - metricsnet

# Logstash: Log Collector and Log Parser
  logstash:
    build: ./logstash
    image: logstash-rsyslog:7.1.1
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - logstash-data:/usr/share/logstash/data
    depends_on:
      - kibana
    ports:
      - '5000:5000'
    networks:
      - logsnet

# ElasticSearch: Database and Search Engine for Logs
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - cluster.name=monitoring-elastic-cluster
      - discovery.type=single-node
    volumes:
      - elasticsearch-storage:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - logsnet

# Kibana: UI and Dashboards for Log Search and Visualization
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    environment:
      CSP_STRICT: 'true'
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    networks:
      - logsnet

networks:
  metricsnet:
  logsnet:

volumes:
  influxdb-storage:
  grafana-storage:
  logstash-data:
  elasticsearch-storage:
