---
version: '3'

services:
  client:
    build: .
    image: sensu-client-plugins:1.4.3
    command: client
    environment:
      CLIENT_NAME: test-client-1
      TRANSPORT_NAME: rabbitmq
      CLIENT_SUBSCRIPTIONS: all
      CLIENT_ADDRESS: 127.0.0.1
      CLIENT_DEREGISTER: 'false'
      CLIENT_KEEPALIVE_HANDLER: 'mailer'
      #para acessar info do host e nao do container:
      HOST_DEV_DIR: /host_dev
      HOST_PROC_DIR: /host_proc
      HOST_SYS_DIR: /host_sys
    volumes:
     - ./checks:/etc/sensu/conf.d/checks
     #Para que o container pegue info de monitoracao do host
     #e nao dele mesmo
     - /dev:/host_dev/:ro
     - /proc:/host_proc/:ro
     - /sys:/host_sys/:ro
    ports:
      - '3030:3030'
    networks:
      - default

networks:
  default:
    external:
      name: monitoringservice_default
