---
version: '3'

services:
  client-single:
    build: .
    image: monitored-host:1.4.3
    command: client
    hostname: compute-pro-09
    environment:
      CLIENT_NAME: compute-pro-09.local
      TRANSPORT_NAME: rabbitmq
      CLIENT_SUBSCRIPTIONS: all
      CLIENT_ADDRESS: 192.168.200.3
      CLIENT_DEREGISTER: 'false'
      CLIENT_KEEPALIVE_HANDLER: 'mailer'
      #para acessar info do host e nao do container:
      #HOST_DEV_DIR: /host_dev
      #HOST_PROC_DIR: /host_proc
      #HOST_SYS_DIR: /host_sys
    volumes:
     - ./sensu:/etc/sensu/conf.d/checks
     - ./rsyslog/rsyslog.conf:/etc/rsyslog.conf
     #Para que o container pegue info de monitoracao do host
     #e nao dele mesmo
     #- /dev:/host_dev/:ro
     #- /proc:/host_proc/:ro
     #- /sys:/host_sys/:ro
    ports:
     #- '514'
      - '3030'
     #- '3030:3030'
    networks:
      - metricsnet
      - logsnet

networks:
  metricsnet:
    external:
      name: monitoring-service_metricsnet
  logsnet:
    external:
      name: monitoring-service_logsnet
